# Use root/example as user/password credentials
version: '3.3'
services:
   db:
     image: mysql:8.0.28
     volumes:
       - db_data:/var/lib/mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: toortoor
       MYSQL_DATABASE: test
       MYSQL_USER: test
       MYSQL_PASSWORD: testtest
volumes:
    db_data: {}
